Repository Selody-project/Frontend, pull requests merged in 2023-08, with the labels that each got.

#107 #104 fix: Fix prettier error
  .eslintrc.json
  package.json
Labels: bug

#109 #108 style: Edit import auto sorted setting
  .eslintrc.json
  package.json
  src/App.jsx
  src/components/Base/BaseModal/BaseModal.jsx
  src/components/Common/CalendarContainer.jsx
  src/components/Common/ScheduleModal/ScheduleModal.jsx
  src/components/FeedPage/FeedMain/FeedMain.jsx
  src/components/Header/FeedHeader/FeedHeader.jsx
  src/components/Header/GroupHeader/GroupHeader.jsx
  src/components/Header/Header/Header.jsx
  src/components/MyPage/PasswordUpdate.jsx
  src/components/MyPage/ProfileSettings.jsx
  src/components/MyPage/SharedSettings.jsx
  src/components/PersonalTodoList/PersonalTodoItem/PersonalTodoItem.jsx
  src/components/PersonalTodoList/PersonalTodoList/PersonalTodoList.jsx
  src/components/SharePage/CreateGroupModal.jsx
  src/components/SharePage/ShareTodoList/ShareTodoList.jsx
  src/main.jsx
  src/pages/GroupSchedulePage.jsx
  src/pages/PersonalSchedulePage.jsx
Labels: Priority 1

#112 111 front task 로그인 페이지 퍼블리싱
  __test__/__mocks__/msw/server.js
  __test__/pagesTest/Errorpage.test.jsx
  __test__/pagesTest/LandingPage.test.jsx
  __test__/pagesTest/LoginPage.test.jsx
  __test__/pagesTest/MyPage.test.jsx
  __test__/pagesTest/PersonalSchedulePage.test.jsx
  __test__/pagesTest/SignUpPage.test.jsx
  __test__/reduxTest/scheduleSlice.test.js
  jest.config.cjs
  package-lock.json
  package.json
  src/assets/icon/ic-google-logo.svg
  src/assets/icon/ic-naver-logo.svg
  src/components/Base/BaseModal/BaseModal.jsx
  src/components/sign/Google.jsx
  src/components/sign/Naver.jsx
  src/features/group/group-invite-service.js
  src/pages/LoginPage/LoginPage.jsx
  src/pages/LoginPage/LoginPage.styles.js
  vite.config.js
Labels: bug, enhancement

#120 #118 feat: reset.css 적용 및 중복 속성 제거
  src/styles/GlobalStyles.js
Labels: enhancement

#125 #123 design: Override color system
  src/styles/theme.js
Labels: enhancement

#122 121 front task header 구현
  __test__/pagesTest/SettingPage.test.jsx
  src/App.jsx
  src/assets/icon/ic-notification-dropdown.svg
  src/assets/icon/ic-profile-dropdown.svg
  src/components/Base/BaseModal/BaseModal.jsx
  src/components/Base/BaseModal/BaseModal.style.js
  src/components/Common/CalendarContainer.jsx
  src/components/Common/CustomCalendar/CustomCalendar.jsx
  src/components/Common/CustomCalendar/CustomCalendar.styles.js
  src/components/Common/ScheduleModal/ScheduleModal.jsx
  src/components/Common/ScheduleModal/ScheduleModal.styles.js
  src/components/Header/FeedHeader/FeedHeader.jsx
  src/components/Header/FeedHeader/FeedHeader.styles.js
  src/components/Header/GroupCreateModal/GroupCreateModal.jsx
  src/components/Header/GroupCreateModal/GroupCreateModal.style.js
  src/components/Header/GroupHeader/GroupHeader.jsx
  src/components/Header/GroupHeader/GroupHeader.styles.js
  src/components/Header/Header/Header.jsx
  src/components/Header/Header/Header.styles.js
  src/components/Header/ProfileDropdown/ProfileDropdown.jsx
  src/components/Header/ProfileDropdown/ProfileDropdown.style.js
  src/components/Header/SubHeader/SubHeader.jsx
  src/components/Header/SubHeader/SubHeader.style.js
  src/components/Notification/NotificationDropdown/NotificationDropdown.jsx
  src/components/Notification/NotificationDropdown/NotificationDropdown.style.js
  src/components/Notification/NotificationItem/NotificationItem.jsx
  src/components/Notification/NotificationItem/NotificationItem.style.js
  src/components/PersonalTodoList/PersonalTodoItem/PersonalTodoItem.jsx
  src/components/PersonalTodoList/PersonalTodoList/PersonalTodoList.jsx
  src/components/Setting/PasswordUpdate.jsx
  src/components/Setting/ProfileSettings.jsx
  src/components/Setting/SettingPageDetail.styles.js
  src/components/Setting/SharedSettings.jsx
  src/components/SharePage/CreateGroupModal.jsx
  src/components/SharePage/ShareTodoList/ShareTodoList.jsx
  src/components/SignUp/SignUpForm/SignUpForm.jsx
  src/features/auth/auth-service.js
  src/features/auth/auth-slice.js
  src/hooks/useScrollLock.jsx
  src/pages/FeedPage.jsx
  src/pages/GroupSchedulePage.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/LoginPage/LoginPage.styles.js
  src/pages/MyPage/MyPage.jsx
  src/pages/PersonalSchedulePage.jsx
  src/pages/Root.jsx
  src/pages/SettingPage/SettingPage.jsx
  src/pages/SettingPage/SettingPage.style.js
  src/pages/SignUpPage/SignUpPage.jsx
  src/pages/index.jsx
  src/store/index.js
  src/styles/GlobalStyles.js
Labels: enhancement

#133 #130 update: Update color system
  src/styles/theme.js
Labels: enhancement
