Repository Selody-project/Frontend, pull requests merged in 2024-01, with the labels that each got.

#174 169 front task refactor tab component
  src/App.jsx
  src/components/Common/Tab/Tab.jsx
  src/components/Common/Tab/Tab.styles.js
  src/components/Header/Header/Header.jsx
  src/components/Header/Header/Header.styles.js
  src/components/Header/SubHeader/SubHeader.jsx
  src/components/Header/SubHeader/SubHeader.style.js
  src/constants/tabConstants.js
  src/pages/PublicRoute.jsx
  src/pages/Root.jsx
Labels: enhancement

#163 issue #162 refactor: BaseModal refactoring
  src/components/Common/BaseModal/BaseModal.jsx
  src/components/Common/BaseModal/BaseModal.style.js
  src/components/Common/ScheduleModal/ScheduleModal.jsx
  src/components/Header/GroupCreateModal/GroupCreateModal.jsx
  src/components/PersonalTodoList/PersonalTodoItem/PersonalTodoItem.jsx
  src/components/Setting/GroupModals/GroupModals.jsx
  src/components/Setting/WithdrawalTab/WithdrawalTab.jsx
  src/components/Ui/BaseAxios.js
  src/components/Ui/BaseCard/BaseCard.jsx
  src/components/Ui/BaseCard/BaseCard.styles.js
  src/features/commonThunk.js
  src/features/group/group-invite-service.js
  src/features/schedule/schedule-service.js
  src/features/user/user-service.js
  src/hooks/useAxios.js
Labels: enhancement, refactoring

#184 issue #183 fix: 아무 요청이던 exipred accessToken을 가질 때 재발급 후 재요청
  src/components/Ui/BaseAxios.js
Labels: bug

#187 issue #186 fix: 토큰 재발급 엔드포인트 요청 무한 중첩 해결
  src/components/Ui/BaseAxios.js
Labels: bug

#188 185 front task 그룹 일정 조회 및 그룹별 유니크한 색 추가
  __test__/pagesTest/PersonalSchedulePage.test.jsx
  src/components/Common/SchedulePage/CalendarContainer/CalendarContainer.jsx
  src/components/Common/SchedulePage/CalendarContainer/CustomCalendar/CustomCalendar.jsx
  src/components/Common/SchedulePage/ScheduleItemList/ScheduleItem/ScheduleItem.jsx
  src/components/Common/SchedulePage/ScheduleItemList/ScheduleItemList.jsx
  src/constants/calendarConstants.js
  src/features/schedule/schedule-service.js
  src/features/schedule/schedule-slice.js
  src/pages/PersonalSchedulePage.jsx
  src/pages/SharedSchedulePage.jsx
  src/utils/calendarUtils.js
Labels: enhancement, refactoring
